### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by UnrealFakes** [izqalan/cy-client#11]
I'm getting this error when downloading a 19.45GB pack (NSFW) - https://cyberdrop.me/a/lSydtfiD. Using Cy Client V1.1.2.0.

Specifically, it throws this error when it reaches the file "Hermione - YouTube Gaming.mp4" which is 3.33GB (the largest in the whole set).

Would be great if we could change the download priority, option to prioritize smaller files first.

**Comment by Gorthezar** [comment]
This also happened to me today just wanted to throw my hat in here.

**Comment by heyitsritesh** [comment]
The same happened with me today, and I'm using v1.1.3.

**Comment by Anequit** [comment]
Should be fixed in the next update!
