### ISSUE TITLE
"unable to connect to remote server"

### ISSUE THREAD

**Issue by Lfren38** [izqalan/cy-client#14]
for some reason downloading some random albums just wont work at all, and ill get an error as stated in the title, no idea what could be the exact issue on my end, wish i could give more information

**Comment by Madlyaza** [comment]
exact same issue, was working fine yesterday.

**Comment by Anequit** [comment]
> exact same issue, was working fine yesterday.
Most likely has something to do with the website not the program itself

**Comment by Anequit** [comment]
Should be fixed in the next update!
