### ISSUE TITLE
Spoonfed :C

### ISSUE THREAD

**Issue by sirspookz** [izqalan/cy-client#15]
I'm really sorry to be asking the most basic things, but how do you start this ? Sorry for wasting your time; help would greatly be appreciated :C

**Comment by izqalan** [comment]
Hello, I just released [v1.1.3](https://github.com/izqalan/cy-client/releases/tag/v1.1.3). you can download the .zip file and run the setup program and it should install the program. you can find the program by typing "Cyberdrop downloader" in your windows search bar.

alternatively you can download cy.client.1.1.3.exe and run it. easier but I can't guarantee it wouldn't break.
