### ISSUE TITLE
Getting error 404 on a file because of charset

### ISSUE THREAD

**Issue by SirErik82** [izqalan/cy-client#19]
https://cyberdrop.me/a/C7zLRzOw

Third file is getting an error because of the ' in the name. The charset used in the app convert the ' to &39; therefore the app says the file does not exist.

Sophie Mudd Reese's RAW.mp4
See screenshot for app error and how it is outputting on the app.

Windows 10 Pro (in French obviously)
Cy-client 1.1.3

![error404](https://user-images.githubusercontent.com/26279432/118223229-f2ddc100-b44e-11eb-98e3-96605cf7b07f.png)

**Comment by izqalan** [comment]
fixed. the [.exe](https://github.com/izqalan/cy-client/releases/download/v1.1.3/cy.client.1131.exe) and [installation zip](https://github.com/izqalan/cy-client/releases/download/v1.1.3/cy_client_1131.zip) are up.
