### ISSUE TITLE
Some downloaded files resulted corrupted

### ISSUE THREAD

**Issue by phaolo2** [izqalan/cy-client#24]
**Describe the bug / Error message**
I tried downloading a few albums, but some of the images resulted corrupted.
(e.g: some images showed only the upper 1\10 part completed)
Is there any integrity checking or automatic retry?

EDIT1: btw this seems quite rare, like one file every 50
EDIT2: but it becomes more frequent with big files (like above 10Mb)

**Desktop:**
 - OS: Windows 7 Pro x64
 - Version 1.1.3.1

**Comment by phaolo2** [comment]
Now I've got the error:
`Received an unexpected EOF of 0 bytes from the transport stream`

And retrying the download didn't skip the existing files.

**Comment by phaolo2** [comment]
And now this error:
`The request was aborted: Could not create SSL/TLS secure channel.`

**Comment by SirErik82** [comment]
I'm getting the same error, on different file on this https://cyberdrop.me/a/MLVkyAcX
![error2](https://user-images.githubusercontent.com/26279432/119035415-8cd8c880-b97d-11eb-8268-8a2dcf9d27d9.png)

**Comment by izqalan** [comment]
I'll keep this open until I release v1.2
