### ISSUE TITLE
Port to avalonia to allow cross platform usage

### ISSUE THREAD

**Issue by Anequit** [izqalan/cy-client#32]
Porting to avalonia wouldn't be a difficult task, but would allow for the downloader to be used in mac and linux.

**Comment by Anequit** [comment]
as well as port to .net core instead of framework for more performance and cross platform compatibility

**Comment by Anequit** [comment]
I cloned the repo and I'm taking a look at the code base to see if if a .net core port is doable.

**Comment by izqalan** [comment]
@Anequit Cool! I'll look into it but I can't promise if I can do it.

**Comment by Anequit** [comment]
> @Anequit Cool! I'll look into it but I can't promise if I can do it.

I don't mind doing it. If you assign me to the issue I can try and replicate the ui as close as possible and wire it up for you.

**Comment by Anequit** [comment]
I won't be able to integrate the titlebar with the system titlebar, so the application styling will be persistent across all operating system. I've tried to create a background panel behind the exit button and such, but they blend the colors and cause it to look really od, so the image above is how it will look 👍🏻

**Comment by Anequit** [comment]
implemented drag and drop on the custom title bar :)

**Comment by Anequit** [comment]
@izqalan There isn't a group box present in avalonia, so i did this. Is this alright?
![image](https://user-images.githubusercontent.com/51097472/127901388-b3b87076-b9dd-4114-95ba-7457157ebc7d.png)
Ignore the red as it's just placeholder, but the download log used to be a group box.

**Comment by Anequit** [comment]
![image](https://user-images.githubusercontent.com/51097472/128913404-985ddc71-e590-41f4-99d3-f08b3e46c75f.png)

Almost done! The only thing that's not finished is wiring up the old downloading code to the UI so it functions properly and getting the two bottom links at the bottom working.

**Comment by Anequit** [comment]
I've been considering refactoring the old codebase to help with identifying issues, but I'll do that in a separate branch when the UI is 100% done and wired up first.

**Comment by Anequit** [comment]
> I've been considering refactoring the old codebase to help with identifying issues, but I'll do that in a separate branch when the UI is 100% done and wired up first.

Will have to refactor it.

**Comment by Anequit** [comment]
![image](https://user-images.githubusercontent.com/51097472/129247595-693a760b-9edc-48a1-ae21-040f3586bffb.png)

Almost done!

**Comment by izqalan** [comment]
@Anequit Good work! I've been busy with another project, I'm sorry I couldn't be of more help to you.

**Comment by Hrxn** [comment]
Any news here?

Is this supposed to work with .NET Core already? I couldn't find a more specific issue, the wiki is empty, and the README does not specify anything either here. 😄

**Comment by Anequit** [comment]
> Any news here?
> 
> Is this supposed to work with .NET Core already? I couldn't find a more specific issue, the wiki is empty, and the README does not specify anything either here. 😄

It was originally on .net framework, but there wasn't .net maui at the time so we moved it to avalonia.
