### ISSUE TITLE
Getting Remote Server Returned an Error : Gateway Timeout

### ISSUE THREAD

**Issue by christ2702** [izqalan/cy-client#34]
Always got this error

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - Version [e.g. 1.2.0.0]

**Screenshots**

**Additional context**
![Capture](https://user-images.githubusercontent.com/21233880/127688094-19a99c14-f965-4866-b245-28397edc5717.JPG)

**Comment by Anequit** [comment]
Appears that it simply timed out while downloading it. I'll try to take a look at it. Can you write down the file it happened it at?

**Comment by Anequit** [comment]
![image](https://user-images.githubusercontent.com/51097472/127691813-acfd091e-48bd-48bc-be11-65b4b6196b34.png)
I was able to replicate it, so I'll take a loot and try to debug it.

**Comment by Anequit** [comment]
@izqalan When I'm finished with the ui I'm going to add some exception handling, so that these issues can be located easier.

**Comment by Anequit** [comment]
I'm going to write a small patch for this bug, but this is just a temporary fix as I'm busy working on another aspect of the program. I'll open a pull request for the patch in a bit.

**Comment by christ2702** [comment]
Hey, I really appreciate it
Thank you

**Comment by izqalan** [comment]
@christ2702 @Anequit merged. Releasing the fix in a bit.

**Comment by izqalan** [comment]
it's up https://github.com/izqalan/cy-client/releases/tag/v1.2.1
