### ISSUE TITLE
Download Progress including file size and Download Speed

### ISSUE THREAD

**Issue by erevs** [izqalan/cy-client#37]
**Is your feature request related to a problem? Please describe.**
I would like to be able to see the current file downloading including the file size and download speed.
**Describe the solution you'd like**
A progress bar or even a simple numerical display would be cool.

Thanks for any help

**Comment by Anequit** [comment]
@izqalan thoughts on this feature?

**Comment by izqalan** [comment]
I have something like this in mind. but I'm not sure if the performance will be impacted since it textbox index needs to keep updating with the latest progress%.

![cy2](https://user-images.githubusercontent.com/24191952/133355356-ef204263-7a9f-4aec-9769-3b219c40b5ad.png)

**Comment by Anequit** [comment]
I'm working on implementing chunked downloads, so something that was 300mb would be split into 100 chunks of 3 million bytes each, and that way if a chunk fails it can be started over instead of starting the whole file over.

**Comment by Anequit** [comment]
Not near ready for a test or anything close to that. I'm still trying to verify the idea would work.

**Comment by Anequit** [comment]
If the chunk idea works out then, tracking download progress would be 100% possible.

**Comment by Anequit** [comment]
> If the chunk idea works out then, tracking download progress would be 100% possible.

Chunks do work and I'll be working on adding the progress to the UI.
