### ISSUE TITLE
Downloads Fail/Skip and Connection Issue

### ISSUE THREAD

**Issue by lordchampagne** [izqalan/cy-client#38]
**Describe the bug / Error message**
First greeted by an error message stating "unable to read data from the transport connection an existing connection was forcibly closed by the remote host", the client will try to download but only to skip/fail.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/88640135/128654700-cfcaae2c-93ee-4b2e-ab79-2e1660371878.PNG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 21H1

**Comment by Anequit** [comment]
@izqalan This could be possibly an issue with the Downloader nuget package used to download files. I suggest a proper rewrite of how files are downloaded using Webclient. I can work on this after finishing the UI.

**Comment by Anequit** [comment]
Should be fixed in the next update!
