### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by Horseclock** [izqalan/cy-client#4]
Is there any way that the program can be set to cut out symbols in album titles. 
Some albums can't be downloaded because windows doesn't allow "?" or "|" in folder names but the cyberdrop albums do.

**Comment by izqalan** [comment]
Good find! unfortunately there's no workaround atm. I'll work on the fix asap.

**Comment by izqalan** [comment]
Hey @Horseclock I've [release ](https://github.com/izqalan/cy-client/releases/tag/v1.1.1) the fix. let me know if you still have any problem.
