### ISSUE TITLE
Value cannot be null.

### ISSUE THREAD

**Issue by Arkham862** [izqalan/cy-client#6]
************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at cyberdropDownloader.CyScraper.GetTitle(HtmlDocument htmlDoc)
   at cyberdropDownloader.CyScraper.<GetUrlsAndDownload>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by Site3op** [comment]
Yeah I'm getting the same thing despite appropriate cyberdrop links. I am able to get the downloader to work if I play around with adding and removing spaces in front/behind the link.

**Comment by izqalan** [comment]
Hi @Arkham862 @Site3op thank you for reporting.

I've ran some tests, it seems like the program unable to reach the site (https://cyberdrop.me) but able to reach https://www.google.com/. I'm assuming there's anti-scraping mechanism going on.

> Yeah I'm getting the same thing despite appropriate cyberdrop links. I am able to get the downloader to work if I play around with adding and removing spaces in front/behind the link.

I'm unable to reproduce this. could you share a screen recording?

**Comment by Site3op** [comment]
It is pretty random, maybe it just happens to be able to connect when I try playing around, but I can never get it to work if I just spam Download over and over without playing around with the link. 
https://user-images.githubusercontent.com/79298242/108465062-eaf2f400-7246-11eb-95c2-2939d80afc0b.mp4

**Comment by Site3op** [comment]
I also did notice that another scrapper using python had troubles scrapping any albums it would only get one of five urls every couple of tries and was inconsistent as well, which is why I came here to try yours.

**Comment by izqalan** [comment]
@Arkham862 @Site3op it should work now. If you face some bugs install the [latest release](https://github.com/izqalan/cy-client/releases/tag/v1.1.2)

**Comment by bertiewils** [comment]
Fixed for me on 1.1.2, thank you

**Comment by Site3op** [comment]
This has been fixed for me. Thank you!
