### ISSUE TITLE
Cannot start from this location because it is already installed from a different location

### ISSUE THREAD

**Issue by Site3op** [izqalan/cy-client#8]
Even after deleting the previous version of cy-client, it seems to just continue saying that. 

[Y8B7SBWT.log](https://github.com/izqalan/cy-client/files/6023010/Y8B7SBWT.log)

**Comment by bertiewils** [comment]
Overwriting the files from the 1.1.1 release with the files from the 1.1.2 release resolved this for me

**Comment by Site3op** [comment]
Thank you!
